version: '3.8'
services:
  app:
    image: python:3.8
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      VIRTUAL_ENV: /app/venv